### ISSUE TITLE
Recursion Problem

### ISSUE THREAD

**Issue by lfelipecunha** [luiscoms/release#2]
When the ComposerIO search composer.json file recursively and reaches "/" (with read permissions), so we have a Fatal Error:

<pre>
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /release/src/Release/IO/ComposerIO.php on line 48
</pre>

This problem is caused by these lines https://github.com/luiscoms/release/blob/develop/src/Release/IO/ComposerIO.php#L61-L63, 'cause dirname function returns same string when receive a "/".

**Comment by luiscoms** [comment]
Merged
